import { FormControl, Validators } from "@angular/forms";
 
export const form_headers = {
    requestNo: null,
    requestDate:  new Date(),
    requestTypeCode:  null,
    supplierCode:  null,
    supplierName:  null,
    reference:  null,
    objective:  null,
    description:  null,
    approved1:  null,
    approver1:  null,
    approverName1:  null,
    approvedDate1: null,
    approver2:  null,
    approved2:  null,
    approvedDate2: null,
    approver3:  null,
    approved3:  null,
    approvedDate3: null,
    approver4:  null,
    approved4:  null,
    approvedDate4: null,
    approver5:  null,
    approved5:  null,
    approvedDate5: null,
    requirementDate: null,
    referenceAdb:  null,
    referenceRfp: null,
    assignedTo:  null,
    payableTo:  null,
    processedByAp:  null,
    processedByGl:  null,
    liquidatedBy:  null,
    quantity: null,
    cost: null, 
    extendedAmount: null,
    refundAmount: null,
    createdBy:  null,
    createdDate: new Date(),
    updatedBy:  null,
    updatedDate: null,
    rstype:  null,
    rfatype:  null, 
    isReferral:false,
    rfpSource: null,
    branchCode: null,
    recommendation: null,
    requestItemsType: null,
    ewt: null
}
